### ISSUE TITLE
allow absolute dir for `routes_dir`

### ISSUE THREAD

**Issue by zhaoyao91** [hsitraka/hapi-auto-route#14]
based on process.cwd is not stable. many times we could use path.resolve(__dirname, './somedir') to  specify clear dir path

**Comment by sitraka-hq** [comment]
Would like to make a pull request for that?

**Comment by sitraka-hq** [comment]
Thank you!

**Comment by zhaoyao91** [comment]
I noticed you updated the README to say that routes_dir **IS** absolute path. 

In fact the merged PR is considered to be compatible with relative path as before. Is that a high level decision to require `routes_dir` to be absolute?
